version: "3.7"
services:
  frontend:
    build:
      context: .
      target: development
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /code/node_modules
      - ./:/code
      - /code/.next